name: CI/CD - Docker Image from DECS Branch

# 1. 실행 조건 변경: 'develop' 브랜치를 대상으로 하는 PR이 닫혔을 때
on:
  pull_request:
    types: [closed]
    branches: [ "develop" ] # 타겟 브랜치

jobs:
  build-and-push:
    # 2. 상세 실행 조건: PR이 '병합'되었고, 소스 브랜치가 'decs'로 시작할 때만 실행
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'decs')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCK_USERNAME }}
          password: ${{ secrets.DOCK_TOKEN }}

      # 3. 태그 추출 방식 변경: 'decs' 접두사 제거
      - name: Generate tag from branch name
        id: generate_tag
        run: |
          # 병합된 브랜치 이름을 가져옴 (예: 'decs251002')
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          
          # 'decs' 접두사를 제거하여 버전만 추출 (예: '251002')
          TAG_VERSION=${BRANCH_NAME#decs}
          
          echo "Extracted tag version: $TAG_VERSION"
          
          # 다음 단계에서 사용할 수 있도록 태그 이름을 GITHUB_OUTPUT에 저장
          echo "TAG_NAME=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dguailab/decs:${{ steps.generate_tag.outputs.TAG_NAME }}
            dguailab/decs:latest
